### ISSUE TITLE
How to get more detailed help of some command?

### ISSUE THREAD

**Issue by MurzNN** [JOJ0/synadm#10]
There is exist a general help command, that shows the help text:
```
synadm -h
```
In script code I see more detailed help text for commands, for example for `room delete` command:
https://github.com/JOJ0/synadm/blob/45b1220747a81d76118ade33fc33a6623e5b3236/synadm.py#L900
But I can't understand how to show it via command line arguments?
I try those:
```
synadm room delete
synadm -h room
synadm -h room delete
```
But no one shows me the detailed help text with list of available arguments.

**Comment by JOJ0** [comment]
Hi @MurzNN,
you have to put the -h after the subcommand you are trying to get help from. Eg:
```
synadm room -h
synadm user -h
```

**Comment by JOJ0** [comment]
Also if there is a subcommand of a subcommand you have to put it after that. But you probably figured that out already:
```
synadm user modify -h
```
I'll close this issue now! Thanks for reporting and all the best!

**Comment by MurzNN** [comment]
Thanks for explaining! In some other tools `-h` in any place works, so I didn't try it at end, now `-h` at end works well!
