### ISSUE TITLE
synadm doesn't work after v0.38 with Click 7.0

### ISSUE THREAD

**Issue by lfom** [JOJ0/synadm#106]
Hi, there.

Thank you for creating and maintaining `synadm`. I have been using it for a while on Ubuntu 20.04 and after I updated today to version 0.41 it stopped working with this error:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/synadm", line 5, in <module>
    from synadm.cli import root
  File "/home/ubuntu/.local/lib/python3.8/site-packages/synadm/cli/__init__.py", line 486, in <module>
    from synadm.cli import room, user, media, group, history, matrix, regtok, notice  # noqa: F401, E402, E501
  File "/home/ubuntu/.local/lib/python3.8/site-packages/synadm/cli/room.py", line 336, in <module>
    def block(helper, room_id, block):
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 173, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1601, in __init__
    raise TypeError('Got secondary option for non boolean flag.')
TypeError: Got secondary option for non boolean flag.
```
Then I noticed this when upgrading:
```
Requirement already satisfied: Click<8.0,>=7.0 in /usr/lib/python3/dist-packages (from synadm) (7.0)
```
And then tried to install only this package (newer version from `pip`), what worked:
```
píp install -U click
```
Now I have this for my user:
```
$ pip list --user      
Package            Version
------------------ -------
click              8.1.3  
click-option-group 0.5.5  
dnspython          2.3.0  
synadm             0.41 
```
I did not find **click** in logs, so I guess that was the version installed by default on Ubuntu 20.04. Maybe the version needs to be updated in the dependencies.

PS: while troubleshooting it seems that the builtin version works with `synadm` up to v0.38 and fails after that.

Regards

**Comment by JacksonChen666** [comment]
@lfom
- What command did you run that caused the error?
- What version of `Click` was installed when the error occurred?
- Do you still have the error after upgrading `Click`?

**Comment by lfom** [comment]
> @lfom
> 
>     * What command did you run that caused the error?
> 
>     * What version of `Click` was installed when the error occurred?
> 
>     * Do you still have the error after upgrading `Click`?

* any `synadm` command
* click 7.0 
* no, everything seems to work fine with click 8.1.3 installed via pip

**Comment by JacksonChen666** [comment]
> ```
> Requirement already satisfied: Click<8.0,>=7.0 in /usr/lib/python3/dist-packages (from synadm) (7.0)
> ```

Well, that's odd...

`v0.41` specifies `Click<9.0,>=7.0`, but your install logs show something else.

Could you try upgrading the `synadm` package through pip? (Did you install synadm outside of pip?)

**Comment by lfom** [comment]
@JacksonChen666 Thank you for taking a look into this. Maybe I was not clear enough, so please let me try to clarify it:

1. `synadm` was installed with `pip` since the beginning 
2. `synadm` works with builtin click (v7.0) up to version 0.38
3.  From `synadm` version 0.39 and up, it shows the same error when I try to run it with any arguments, what as fixed after updating click via `pip`.

**Comment by JacksonChen666** [comment]
Ok so I just installed `Click==7.0` and it definitely does not work, giving the same error message (not stacktrace). 7.1 seems to work though.

I will create a PR to fix this issue. @JOJ0 just a heads up for that.

**Comment by JacksonChen666** [comment]
63fa8e5d7366ebc73696af8fbe1292538fb3fcf3 is the first commit to cause the issue (yes, it's mine, i have no idea how it's causing issues, that's for later)

**Comment by JacksonChen666** [comment]
Anyways, thanks for reporting this issue!

**Comment by JOJ0** [comment]
Thank you both for reporting and digging into a fix! We'll release this shortly!
