### ISSUE TITLE
User list function breaking change

### ISSUE THREAD

**Issue by JacksonChen666** [JOJ0/synadm#127]
> This was a breaking change for us (using `synadm` for scripting). The `user_list_paginate` function uses `user_list`, but the call of `user_list` was not updated to include some setting for the admin filter, so calling `user_list_paginate` inherently fails.
> 
> Correct me if I'm wrong, but to me it looks like this may be the problem, so potenially just fixing api.py:471 or extending `user_list_paginate`'s signature with the admin filter would be sufficient. If doing the latter, please consider putting a default value for the admin filter so there's no permanent breaking change for others using the function :)
> 
> Thanks for your work on synadm, we highly appreciate it!

_Originally posted by @a-0-dev in https://github.com/JOJ0/synadm/issues/123#issuecomment-1719890583_

**Comment by JOJ0** [comment]
Hi and welcome back @a-0-dev :-) thanks for the detailed report! That helps!
