### ISSUE TITLE
Synapse returned status code 400 - Can only delete local media

### ISSUE THREAD

**Issue by ZhenyaPav** [JOJ0/synadm#142]
I'm unable to use `synadm media delete`, as it returns this, without deleting anything:
```
WARNING Synapse returned status code 400
errcode  M_UNKNOWN
error    Can only delete local media
```

The synapse server was installed using matrix-docker-ansible-deploy.

**Comment by ZhenyaPav** [comment]
> What's the full `synadm` command that you ran?

`synadm media delete -d 3`

**Comment by JOJ0** [comment]
Can you show us a 

`synadm -vv media delete -d 3`

maybe remove secrets before posting

**Comment by ZhenyaPav** [comment]
`synadm -vv media delete -d 3`
```
DEBUG Config entry read. user: (username)
DEBUG Config entry read. token: REDACTED
DEBUG Config entry read. base_url: http://192.168.(local ip):8008
DEBUG Config entry read. admin_path: /_synapse/admin
DEBUG Config entry read. matrix_path: /_matrix
DEBUG Config entry read. timeout: 30
DEBUG Config entry read. server_discovery: well-known
DEBUG Config entry read. homeserver: matrix.(domain name)
DEBUG Config entry read. ssl_verify: True
DEBUG Config entry read. format: human
DEBUG Formatter in use: human - <function humanize at 0x7fad27985b20>
DEBUG Received --before-days: 3
INFO  Deleting local media older than timestamp: 1709750339095,
INFO  which is the date: 2024-03-06 20:38:59.095000
INFO  Querying post on http://192.168.(local ip):8008/_synapse/admin/v1/media/matrix.(domain name)/delete
WARNING Synapse returned status code 400
errcode  M_UNKNOWN
error    Can only delete local media
```

I think it might be caused by the fact that the server is running on a local machine, with a VPS being used as a proxy. I left the Admin API accessible only through local network intentionally.

**Comment by ZhenyaPav** [comment]
> Possible workaround: Run `synadm config`, and when you see this:
> 
> ```
> Homeserver name (auto-retrieval or matrix.DOMAIN):
> ```
> 
> Enter just the domain name without the `matrix.` part. Then use `synadm media purge` if you want to delete old remote media, or use `synadm media delete` for deleting local media.
> 
> (I'll write a full explanation of the issue later. It seems to be with `synadm config` being confusing for the user, and apparently a deprecation we seemed missed on the [synapse admin local media delete API](https://element-hq.github.io/synapse/latest/admin_api/media_admin_api.html#delete-local-media-by-date-or-size))

This seems to fix the issue
