### ISSUE TITLE
User modify JSONDecodeError

### ISSUE THREAD

**Issue by rschrenk** [JOJ0/synadm#150]
I try to create a test user account using `synadm --non-interactive user modify -n "Test" test`, but unfortunately I receive

```
Current user account settings:
WARNING Synapse returned status code 400
{
    "errcode": "M_UNKNOWN",
    "error": "Can only look up local users"
}
User account settings to be modified:
display_name: Test
WARNING Synapse returned status code 405
ERROR JSONDecodeError while querying Synapse: Expecting value: line 1 column 1 (char 0)
User could not be modified/created.
```

The same error appears, when I use

`synadm --non-interactive user modify -n "Test" '@test:matrix.___MYDOMAIN___'`

Is this a bug in synadm or am I doing anything wrong? I checked the documentation multiple times, but I cannot find a mistake.

**Comment by rschrenk** [comment]
Thank your for the fast response. I switch to using the APIs through CURL requests directly...

**Comment by JOJ0** [comment]
> Thank your for the fast response. I switch to using the APIs through CURL requests directly...

If you ever come back to using the admin api via synadm again @rschrenk, as @JacksonChen666 suggested, starting a synadm comman with global option -vv will always give you the actual api call in detail :-)

**Comment by JOJ0** [comment]
Is matrix.something really your servers name, often people configure their Synapses to be just the domain name.

So for referencing a user, instead of

```
@test:matrix.___MYDOMAIN___

```

you would use

```
@test:___MYDOMAIN___

```
