### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Bubu** [JOJ0/synadm#21]
This project currently has no license, thus packaging it somewhere isn't possible. Could you add a license file?

**Comment by JOJ0** [comment]
will do, you planning packaging it for Debian? just being curious :-)

**Comment by Bubu** [comment]
Archlinux :)

**Comment by JOJ0** [comment]
yes! nice!!! Just can't decide wether I wanna go gpl or bsd -ish.....

**Comment by rht** [comment]
Or Apache2, like synapse: https://github.com/matrix-org/synapse/blob/develop/LICENSE

**Comment by JOJ0** [comment]
apache2 is a kind of bsd-ish license, right?
it's really hard to decide what's important to me but I think I'll go with gpl-3

**Comment by JOJ0** [comment]
hi @Bubu license file added. happy packaging😀 if you really package it, give me a note here and I'll mention it in the readme. thanks!

**Comment by JOJ0** [comment]
> apache2 is a kind of bsd-ish license, right?

no it's actually not really. it's a permissive license too but apache is much more detailed and also cares about patent rights. but after reading a lot about licenses I am not sure if I really understand everything and can make correct decissions.

so is still think there's nothing wrong with gpl cause compared to above licenses it forces the developers to keep the source open and not change the license at any time. 

not sure if it would bother matrix people though and wondering why a lot of projects choose apache these days

> 
> it's really hard to decide what's important to me but I think I'll go with gpl-3

**Comment by Bubu** [comment]
Thanks for adding the license, I packages the -git version here: https://aur.archlinux.org/packages/synadm-git/ :)

**Comment by Bubu** [comment]
> not sure if it would bother matrix people though and wondering why a lot of projects choose apache these days

I think the main driver for that is that organizations are afraid of enterprises not being able to run their project (i.e. synapse) if it were GPL/AGPL licensed as those enterprises are mostly strongly opposed to running/deploying/building on any GPL/AGPL code. i.e. https://opensource.google/docs/using/agpl-policy/

(In my personal opinion, gpl and especially agpl for server side code is a perfectly fine license... but anyway.)
