### ISSUE TITLE
default output format not working

### ISSUE THREAD

**Issue by Bubu** [JOJ0/synadm#22]
On first start it asks for a default output format (I put json) but subsequently it always outputs in yaml mode. Manually specifying the output format works correctly.

**Comment by JOJ0** [comment]
aha interesting, thanks for letting me know. just checked. it's the same with all other output options. the configured one is not used, it's always yaml by default.

BTW you can always reconfigure and overwrite specific settings only without having to reconfigure everything. just `synadm config`

**Comment by JOJ0** [comment]
Hi @Bubu, this is fixed now, please give it a try and report back if it works for you. Thanks!

**Comment by JOJ0** [comment]
Also nice new feature introduced together with the fix: Abbreviation of output formats is now possible when wanting to quickly override via cli option, e.g: `synadm -o j room search test`
