### ISSUE TITLE
synadm user membership: There should be an option to display room alias if applicable

### ISSUE THREAD

**Issue by rht** [JOJ0/synadm#25]
As of now whenever I do `synadm user membership @user:host.com`, I got
```
joined_rooms:
- '!oBvIoUsLyNoTaNiD:host.com'
- '!HaHaHa:host.com'
total: 3
```

for yaml output. This can't be made sense of by humans. Better if there is a flag to display aliases (if applicable) instead.

**Comment by JOJ0** [comment]
yes definitely good idea but I need to think about how to realise it. Having a flag that enables this "additional functionality" is essential as one might use the output of these room ID's in consecutive batch outputs....like with using --batch and "jq" filtering.

probably a `room details`command/api call could help gathering the room name!

**Comment by JOJ0** [comment]
@rht have a look, I finally implemented this feature. Thanks for the idea and possibly a review in advance!
