### ISSUE TITLE
add user media command

### ISSUE THREAD

**Issue by Bubu** [JOJ0/synadm#29]
https://github.com/matrix-org/synapse/blob/develop/docs/admin_api/user_admin_api.rst#list-media-of-an-user

I actually have a patch implementing this... need to clean it up a bit. :tada:

**Comment by JOJ0** [comment]
that’s great! Please put it where all the other media commands are.

the current media list command should move room id to an option. user id should be another option. mutually exclusive.

on the long run I’d like to find a way to put such commands hat fit in more than one subcommand somehow aliased so there is eg a `room media list` command as well as a `media list -r` command.

**Comment by JOJ0** [comment]
and yeah wasnt aware of this api. it is  not released yet, right?

please also add it to the commands list in the readme together with your pr. thanks!

**Comment by Bubu** [comment]
I implemented it as `user media` as that made the most sense (it's part of synapse user admin api). (And yes, the api is released, I used it about a week or so ago.)

**Comment by JOJ0** [comment]
Would it be thinkable for you to reimplement it as `synadm media list -u` or too much hassle? because only then it would fit the current behaviour. and as said: i will add an alias later!

but basically i am with you and before implementing all the media commands i was questioning exactly this. some commands just fit in several places

**Comment by JOJ0** [comment]
Hi @Bubu do you still think you could implement this? If it's quicker for you, please implement as you have it already (`synadm user media list`). I will handle fix it to have it available in both "command places" then. Thanks. If you don't find the time currently but want to pospone or will never find the time, please tell me, it's all ok, just asking for an update and your thoughts on the matter :-)

**Comment by Bubu** [comment]
Sorry swamped with other stuff currently, it's unlikely that I get around to this in the forseeable future.

What I did just now though is grab the related commits for this from my local branch, squash them together and this should be it:

Feel free to adapt that to current master or solve it in a different way. I just don't want to be blocking anything here :-).

```
commit 7c3643ecfab4ecc75751668790d75b86307d5ad1
Author: Marcus Hoffmann <bubu@bubu1.eu>
Date:   Mon Feb 15 21:50:09 2021 +0100

    add user media command

diff --git a/synadm/api.py b/synadm/api.py
index a99861b..9d73d27 100644
--- a/synadm/api.py
+++ b/synadm/api.py
@@ -65,6 +65,14 @@ class SynapseAdmin:
         """
         return self.query("get", f"v1/users/{user_id}/joined_rooms")
 
+    def user_media(self, _from, _limit,  user_id):
+        """ Get a given users uploaded media
+        """
+        return self.query("get", f"v1/users/{user_id}/media", params={
+            "from": _from,
+            "limit": _limit,
+            })
+
     def user_deactivate(self, user_id, gdpr_erase):
         """ Delete a given user
         """
diff --git a/synadm/cli/user.py b/synadm/cli/user.py
index 7fac554..c6fdd9a 100644
--- a/synadm/cli/user.py
+++ b/synadm/cli/user.py
@@ -156,6 +156,32 @@ def membership(helper, user_id):
     else:
         helper.output(joined_rooms)
 
+@user.command()
+@click.argument("user_id", type=str)
+@click.option(
+    "--from", "-f", "from_", type=int, default=0, show_default=True,
+    help="""offset media listing by given number. This option is also used for
+    pagination.""")
+@click.option(
+    "--limit", "-l", type=int, default=100, show_default=True,
+    help="limit media listing to given number")
+@click.pass_obj
+def media(helper, from_, limit, user_id):
+    """ list all media uploaded by a user. Provide matrix user ID
+    (@user:server) as argument.
+    """
+    media = helper.api.user_media(from_, limit, user_id)
+    if media is None:
+        click.echo("Media could not be fetched.")
+        raise SystemExit(1)
+    if helper.output_format == "human":
+        click.echo("User has uploaded {} media blobs."
+                   .format(media["total"]))
+        if int(media["total"]) != 0:
+            helper.output(media["media"])
+    else:
+        helper.output(media)
+
 
 @user.command(name="search")
 @click.argument("search-term", type=str)
```

**Comment by JOJ0** [comment]
thanks a lot, that helps! will try to implement the command in both places.

**Comment by JOJ0** [comment]
Hi @Bubu, I implemented this command now with the help of your draft. It's available as `synadm user media` and also `synadm media list -u`
Listing media by room was changed to now be `synadm media list -r`
It's in master, give it a try and tell me what you think and most of all if it works.
thanks!

**Comment by JOJ0** [comment]
https://github.com/JOJ0/synadm/blob/8c33a454cebe4b2d5d60ef335f41a4604ea8c40e/synadm/cli/media.py#L35
https://github.com/JOJ0/synadm/blob/8c33a454cebe4b2d5d60ef335f41a4604ea8c40e/synadm/cli/user.py#L351

**Comment by JOJ0** [comment]
HI @Bubu by any chance you found the time to upgrade and have a look if the feature works for you?
Anyway, I am closing this issue since it's released by now: https://github.com/JOJ0/synadm/releases/tag/v0.28

If you have any feedback, feel free to report back here. Thanks for the draft again! Appreciated! :-)
