### ISSUE TITLE
auto discover own server name

### ISSUE THREAD

**Issue by Bubu** [JOJ0/synadm#30]
The media delete apis need the own server name to be given as an argument.

I have solved this by instead grabbing it via server_name = requests.get(f"{self.base_url}/_matrix/key/v2/server").json()['server_name'] instead. If you want I can submit a patch for this.

**Comment by JOJ0** [comment]
hi, nice idea and is on the toddo list already. If you implement it, it should be done with keeping in mind that regular matrix calls should be available to other commands too. I was thinking of moving the query function out of SynapseAdmin into a HttpRequests class and subclassin SynapseAdmin and MatrixClient classes. The matrix api base path should be made configurable, analog to the current admin_path config directive.

not on a proper computer right now, so a little much to explain but best you submit a draft pr and we work from there? It will perhaps be several PRs. First could be the subclassing. next makeuse of the new api feature in the media handling methods.

**Comment by rht** [comment]
Or discover it during `synadm config` and then write to synadm.yml in `server_name` field.

**Comment by Bubu** [comment]
I think I'll leave you to designing how this should work exactly. I have basically only this one line I posted above plus making the command not require the argument. :)

**Comment by JOJ0** [comment]
@Bubu alright I was thinking about suggesting somethign similar already! I will implement basic support for matrix client calls and make the urlprefix configurable as mentioned.

Is it ok if I get back to you when I am finished and you put in your line accordingly in a PR?

**Comment by JOJ0** [comment]
Hi @Bubu I implemented a MatrixClient class you can use for your matrix client call. Have a look: 
https://github.com/JOJ0/synadm/commit/884b32e58547d5e203afb82f14d489b824c38bf3

If you need it from CLI level, it is available in the helper object as helper.matrix_api (similar to admin api methods, they are available as helper.api)

If you want to use MatrixClient inside SynapseAdmin you'd need to instantiate it in there. 

I just built this and didn't have much time for testing - at least I think I didn't break current behaviour - well, the new class is not really put to use anywhere yet ;-) Please get back to me if something is weird! Thanks a ton!

**Comment by JOJ0** [comment]
> I have solved this by instead grabbing it via `server_name = requests.get(f"{self.base_url}/_matrix/key/v2/server").json()['server_name']` instead. If you want I can submit a patch for this.

one thing I wanted to note: I made the default for the matrix client api "/_matrix/client" - you seem to have a different path configured here "/_matrix/key/"

make sure you reconfigure and set this config directive to your configured matrix client path: `synadm config`

PS: Sorry I accidentally pressed the wrong button and edited your original question instead of quoting a reply....anywhere think I reverted it to what you original wrote :-)

**Comment by Bubu** [comment]
> one thing I wanted to note: I made the default for the matrix client api "/_matrix/client" - you seem to have a different path configured here "/_matrix/key/"

This is actually part of the S2S api: https://matrix.org/docs/spec/server_server/r0.1.4#retrieving-server-keys

**Comment by JOJ0** [comment]
hi @Bubu thanks for pointing this out! My actual Matrix API know-how is lacking :-) Alright I fixed this by renaming the new class from MatrixClient to Matrix and the path to just _matrix/
Should be fine now! Yeah I know the time problem just too well! ;-) Don't worry, we are not on the run! All good!

**Comment by JOJ0** [comment]
Hi @Bubu, I implemented this for media delete: https://github.com/JOJ0/synadm/commit/0a96a186c0b3686ac6128255a73a20f47db95888
What do you think?

**Comment by Bubu** [comment]
As far as I can see that looks all good :).

**Comment by JOJ0** [comment]
Actually the docstring was wrong. My server_name method does explicitely return the server name as a string only and not the whole thing the keys api responses. Anyway, peanuts, corrected that.

Working on the quarantine api right now. This is what I came up with so far:
```
jojo@jum ~/synadm (media) $ synadm -v -o pprint media quarantine -i 'zdkkcUmbHPoPKkvCyFMTDNOB' -s "some.remote.server"
INFO  Querying post on http://localhost:8008/_synapse/admin/v1/media/quarantine/some.remote.server/zdkkcUmbHPoPKkvCyFMTDNOB/
{}
jojo@jum ~/synadm (media) $
jojo@jum ~/synadm (media) $ synadm -v -o pprint media quarantine -i 'zdkkcUmbHPoPKkvCyFMTDNOB'
INFO  Querying get on http://localhost:8008/_matrix/key/v2/server
INFO  Querying post on http://localhost:8008/_synapse/admin/v1/media/quarantine/peek-a-boo.at/zdkkcUmbHPoPKkvCyFMTDNOB/
{}
jojo@jum ~/synadm (media) $
```

So the behaviour is:
  - No --server-name option is given: Assume we want to quarantine local media and fetch the server name.
  - --server-name option is present: Assume we want to quarantine remote media and use value in the request

Weird thing about the quarnatine API is that it ALWAYS returns an  empty json string. No errors, nothing, it just doesn't care. Guess we'll have to live with that.

**Comment by JOJ0** [comment]
Merged this into master. Thanks again for the idea and draft!
