### ISSUE TITLE
<user id> arguments: Add option to accept only the username

### ISSUE THREAD

**Issue by rht** [JOJ0/synadm#31]
For humans, having to type `@rht:matrix.domain.com` every time is tedious. Would be nice if users can just type `rht`.

**Comment by JOJ0** [comment]
yeah great idea I was thinking the same already. It is tedious to always type the same domain name all over again. If you wanna submit a PR make sure it is available for both, humans and machines. the original longish username might want to be used in scripting command pipelines. so it actually should be configurable somehow. by global switch and to make default in config.

**Comment by rht** [comment]
What I have in mind is for the code to detect whether it is a full user id or just a username (e.g. by looking for both '@' and ':') and take action accordingly (add '@' and domain name if it is a shorthand, do nothing otherwise).

**Comment by rht** [comment]
There is another complication if `base_url` is a localhost though.

**Comment by JOJ0** [comment]
this should be implemented first: https://github.com/JOJ0/synadm/issues/30
then youre fine 😀

**Comment by JOJ0** [comment]
@rht hi, long time no see, but we finally implemented this feature,. It's in master, give it a try and tell us what you think :-)

**Comment by rht** [comment]
I just tested it. It works like a charm! :tada:

**Comment by JOJ0** [comment]
thanks for testing!! 😀
