### ISSUE TITLE
Delete join/leave messages from specific room

### ISSUE THREAD

**Issue by githuberyt** [JOJ0/synadm#34]
Hello 

if you could add a feature to delete or purge join/leave messages from a specific room that will be helpful to big announcements rooms

**Comment by JOJ0** [comment]
Are you sure this is possible using the Synapse admin API's? You can always find a link to the API docs here: https://github.com/JOJ0/synadm#implementation-status--commands-list

If not it is perhaps possible using the Matrix Client API, but that is currently not the focus of synadm, it started out as a tool covering the admin api of Synapse. Basic functionality is there though but no enduser commands yet: https://github.com/JOJ0/synadm/blob/771e533402b06b02194d3e77874556e5ae4dd5c1/synadm/api.py#L85
