### ISSUE TITLE
Update to use new API for deleting a room

### ISSUE THREAD

**Issue by rht** [JOJ0/synadm#37]
Currently, the old POST method is used: `self.query("post", f"v1/rooms/{room_id}/delete", data=data)` (https://github.com/JOJ0/synadm/blob/master/synadm/api.py#L384).

The new route is
`DELETE /_synapse/admin/v1/rooms/<room_id>`.

See https://github.com/matrix-org/synapse/pull/9889.

**Comment by JOJ0** [comment]
Hi @rht , thanks a lot for the hint. If you find the time a PR would be welcomed, if not I hope deprecation will last longer. I currently try to finally put out a new version with focus on "login as user and related topics".

**Comment by JOJ0** [comment]
Finally fixed this. Thanks for the hint @rht!
