### ISSUE TITLE
delete all media files uploaded by specific user

### ISSUE THREAD

**Issue by githuberyt** [JOJ0/synadm#38]
there should be an option to delete all files uploaded by specific user to prevent spammers from flooding the servers with uploading files continuously

**Comment by JOJ0** [comment]
I think you asked this already: https://github.com/JOJ0/synadm/issues/35

You can solve it using `synadm user media` and `synadm media delete`

Do you have little shell scripting expertise?

Does that help?

**Comment by JOJ0** [comment]
I would do something like this:

First get a list of all the media ids:
```
$ synadm -o yaml user media @testuser1:peek-a-boo.at | grep media_id | cut -d ":" -f 2
 zdkkcUmbHPoPKkvCyFMTDNOB
 ZTxHWcvUUBSuSTNixMGEzeyj
$
```

If that works put a loop around it that deletes it:

```
jojo@jum ~ $ for media in $(synadm -o yaml user media @testuser1:peek-a-boo.at | grep media_id | cut -d ":" -f 2); do echo synadm media delete -i $media; done
synadm media delete -i zdkkcUmbHPoPKkvCyFMTDNOB
synadm media delete -i ZTxHWcvUUBSuSTNixMGEzeyj
jojo@jum ~ $
```

(Remove the echo in the body of the loop to really do it)

Does that help?

**Comment by JOJ0** [comment]
or you use jq to get the media id's:
```
$ synadm -o json user media @testuser1:peek-a-boo.at | jq '.media | .[].media_id'
"zdkkcUmbHPoPKkvCyFMTDNOB"
"ZTxHWcvUUBSuSTNixMGEzeyj"
```
HTH

**Comment by githuberyt** [comment]
Thank you for your help 

it will be great if you managed to add this option to synadm

**Comment by JOJ0** [comment]
@githuberyt have you tried the --limit option of synadm user media? find out the total count of medias first then give it to --limit. Also we where discussing your question and possibilites a little on #synadm:peek-a-boo.at, you might wanna join.

**Comment by JOJ0** [comment]
``
> $ for media in $(synadm -o yaml user media @testuser1:peek-a-boo.at | grep media_id | cut -d ":" -f 2); do echo synadm media delete -i $media; done
> synadm media delete -i zdkkcUmbHPoPKkvCyFMTDNOB
> synadm media delete -i ZTxHWcvUUBSuSTNixMGEzeyj
> $
> ```

have you tried that loop? (without the echo it does actually do it)?
also add the --limit option to the `synadm user media part` - just set it to a very hight number. So in the end you have something like that:

```
for media in $(synadm -o yaml user media @testuser1:peek-a-boo.at --limit 27000 | grep media_id | cut -d ":" -f 2); do echo synadm media delete -i $media; done
```

**Comment by githuberyt** [comment]
Thank you so much this what i was looking for the past two months
