### ISSUE TITLE
Deactivating multiple users at once

### ISSUE THREAD

**Issue by Ascurius** [JOJ0/synadm#56]
Hello,

Out of convenience, I am missing a feature for deactivating multiple users at once, preferbly based on a given regular expression or any other kind of matching pattern.

For this to work, all users must be queried and for each it must be check if the MXIDs localpart matches the regular expression. I assume that the ```list``` command can not be used for this at its current implementation. The first problem is, that the API limits how many users are returned and as far as I know there is no way of telling the API ro return all users without limit in one request. Second, the current way of filtering for users during the ```list``` command is not exactly the same as a pattern matching, since the fitler option probably only checks wheter a user ID contains a given substring or not, which is not exactly what I am looking for.

After the query is finished, the deactivate command has to take the list of user IDs returned by the modified ```list``` command and deactivate each of the accounts.

Off course this feature is entirely optional and is not coverd directly by the API at all.

**Comment by JOJ0** [comment]
Hi, nice feature idea and probably particularly useful for admins fighting spammers. FWIW the `user list` command's filter option (`-n`) passes directly to the API and thus supports what's implemented there: https://github.com/JOJ0/synadm/blob/master/synadm/api.py#L345

To get a solution for now, have you tried an approach using the list command, jq and other commandline tools to solve your requirement already?

**Comment by Ascurius** [comment]
>To get a solution for now, have you tried an approach using the list command, jq and other commandline tools for mass deletions?
I have not tested this appraoch yet, but I will do it in the near future and come back to report on viability of this appraoch.

**Comment by jlj77** [comment]
Cool, yeah, I'll try this approach shortly. I've retired a couple of bridges that've left my little homeserver with over 8000 defunct accounts. I'm sure I'll need to play nice with the rate limiting you mentioned, but yes, the example under Advanced Usage in your docs had me thinking about going down this route already. 👍

**Comment by JOJ0** [comment]
@jlj77 if it works for you please share here or to n #synadm:peek-a-boo.at. I'd love to add it to the adv usage topic :-)
