### ISSUE TITLE
Reduce postgresql database size?

### ISSUE THREAD

**Issue by rajil** [JOJ0/synadm#65]
Hello,

My synapse postgres database is consuming quite a bit of space. Is there any way to find out which room is the reason and how can i trim it down?

Thanks

**Comment by JOJ0** [comment]
Not sure if synadm can help with that. It doesn't access the database. It operates through rest api only.

I am not sure what causes there are for a db growing fast. I you find out typical reasons, synadm might help localize them though.

**Comment by JacksonChen666** [comment]
`synadm` (or the synapse admin API) itself cannot do much about reducing space, except for deleting rooms (hint: delete (but not block) rooms with 0 `joined_local_members`) and deleting old media.

in case you'd like a guide for that, i have one: http://jacksonchen666.com/posts/2022-12-03/14-33-00/

@JOJ0 you should close this issue, as it is not related to `synadm`.
