### ISSUE TITLE
Config file/directory is created world-readable

### ISSUE THREAD

**Issue by ilmari** [JOJ0/synadm#7]
The `~/.config/synadm.yaml` file (and the `~/.config/`directory, if it doesn't already exist) is created with default permissions, so with a typical `umask` ends up world-readable. But it contains the admin user's access token, so should be explicitly created with mode `0o600` (or `0o700` for the directory).

**Comment by JOJ0** [comment]
Hi, thanks a lot for mentioning this fact. It is already explicetly stated in the readme. Fiddling with permissions is out of scope of synadm and should be handled by the admin. See:

**Comment by JOJ0** [comment]
@ilmari you don't have any opinion on this?

**Comment by JOJ0** [comment]
Alright I fixed it for posix type OS's. All other will get a warning. What do you think about this solution? 6822945?
