### ISSUE TITLE
Unable to delete room

### ISSUE THREAD

**Issue by jahway603** [JOJ0/synadm#70]
I'm trying to use synadm to delete a room from my server, but I keep getting that the following:

```
$ synadm room delete OMITTED-ROOM_ID
WARNING Synapse returned status code 404
errcode  M_NOT_FOUND
error    Room not found
WARNING Synapse returned status code 404
Traceback (most recent call last):
  File "/usr/local/bin/synadm", line 33, in <module>
    sys.exit(load_entry_point('synadm==0.34', 'console_scripts', 'synadm')())
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dietpi/.local/lib/python3.9/site-packages/synadm/cli/room.py", line 249, in delete
    ctx.invoke(members, room_id=room_id)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click-7.1.2-py3.9.egg/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/dietpi/.local/lib/python3.9/site-packages/synadm/cli/room.py", line 206, in members
    .format(room_members["total"]))
KeyError: 'total'
```

I then tried updating my synadm, but was still unable to delete the room.

I then tried creating a completely new room and synadm won't delete it either.

It doesn't matter what I use for ROOM_ID or if I use ROOM_ID:server-name or anything - it all fails.

Neither `synadm room delete -h` nor the Github README give me any useful information about what ROOM_ID needs to be syntax-wise. Is there special syntax for the ROOM_ID?

I figured my test case with deleting a newly created room would give me the info I need, but it's all failing.

**Comment by JOJ0** [comment]
syntax for room id is !xxx123:matrixservername

you have to put that in single quotes, otherwise your shell might interpret the special character ! for something else.

weird error. what version of synadm? how installed?

and what synapse version?

**Comment by JOJ0** [comment]
also: launching synadm -vv .. might reveal helpful information
HTH

**Comment by JOJ0** [comment]
@jahway603 another hint coming up: Do `synadm room list` and `synadm room members ...` and `room details ...` commands work? BTW: The regular delete command (without using the --batch switch) is also requesting members and other details beforehand to provide the user with a detailed display of what exactly is going to be deleted. The error might as well already happen at this stages. Please provide more details, otherwise I won't be able to help. Thanks in advance and HTH.

**Comment by jahway603** [comment]
Alright, I just tried the single quotes and was able to delete the test room I created. Synadm is the latest and I have it installed via "git installation" from the README.

Odd that I still have the initially reported 404 issue whey trying to "delete" the "GrapheneOS Off Topic" room [!tgbPIxPlvGiwpsGJuu:matrix.org]

Then I tried to "delete" the "GrapheneOS" room and got the following error:
```
$ synadm room delete '!SayHlEYXdrpSerhLMC:matrix.org'
room_id               !SayHlEYXdrpSerhLMC:matrix.org
name
canonical_alias
joined_members        0
joined_local_members  0
version               6
creator               @strcat:matrix.org
encryption
federatable           True
public                False
join_rules
guest_access
history_visibility
state_events          12725
avatar
topic
joined_local_devices  0
Total members in room: 0
Are you sure you want to delete this room? (y/N): y
ERROR ReadTimeout while querying Synapse: HTTPConnectionPool(host='localhost', port=8008): Read timed out. (read timeout=7)
Room not deleted.
```

To summarize, I was able to use the single quotes to delete the test room but the two "problem rooms" I can't seem to be rid of them using synadm. Is there another way to remove these rooms?

**Comment by JOJ0** [comment]
try increasing the timeout via synadm config

**Comment by JOJ0** [comment]
Hi @jahway603 did that work out for you?

**Comment by jahway603** [comment]
Thank you for the changes you've made to synadm. It appears the issue I was having was caused by something client-related, as once I cleared the cache of both the Element Android & Desktop apps the rooms were not there anymore. Now I also do not see them on my server anymore with `synadm room list`. Thank you again for creating and maintaining this great tool.
