### ISSUE TITLE
Add `-y` option for force answer "Yes" when using synadm tool in other scripts

### ISSUE THREAD

**Issue by MurzNN** [JOJ0/synadm#9]
Will be good to add `-y` option for force answer "Yes" without user interactions when using `synadm` tool in other scripts.

**Comment by JOJ0** [comment]
Hi again, thanks for the suggestion, it's a good one. A scripting mode is planned for one of the next synadm releases already :-)

**Comment by JOJ0** [comment]
Hi again, please check out the latest master version. A global flag --batch was introduced. I don't think that it is entirely stable yet, there might be some commands that still have interactivity in them and should be changed.

It would help if you give the batch flag a try and test it with several commands. Especially modify/deactivate/delete kind of things have interactive questions. Please try how they react with the new flag.

I'll reopen this issue now. Please report your findings here! Thanks a ton!

**Comment by JOJ0** [comment]
@MurzNN works for you?
