### ISSUE TITLE
Investigate why we allow empty string as output format

### ISSUE THREAD

**Issue by JOJ0** [JOJ0/synadm#95]
Output format choices seem to make  it possible to use `-o ''` that doesn't seem useful but let's investigate / ask gitlens/gitblame if there maybe was a reason once:

https://github.com/JOJ0/synadm/pull/92/files#r1116809427

**Comment by JacksonChen666** [comment]
hold on... the default option is ""?

commit of interest: df22ea8

**Comment by JOJ0** [comment]
Thanks for your investigation! Interesting...maybe this choice of default has something to do with initial setup. Just guessing. You wanna test what happens when this default is set not empty string, no config exists yet, and any synadm command is lauched? Per design the configurator should launch automatically then.

**Comment by JOJ0** [comment]
Aaaahh got it! This option is to understand as an override for the setting in config.yaml, thus by default it is "nothing"

To be able to use the choices feature of click I _think_ I had to design it that way.

**Comment by JOJ0** [comment]
Thanks for the investigation again. I think this is done and works as designed.
