### ISSUE TITLE
Special internal room IDs breaks some commands

### ISSUE THREAD

**Issue by JacksonChen666** [JOJ0/synadm#96]
A user [could not delete a room](https://matrix.to/#/%23synadm%3Apeek-a-boo.at/%24LcH3oCnbiOaVRcMvPZp11fT0SruL1rjfpWd8MVVpXLw?via=jacksonchen666.com&via=maclemon.at&via=matrix.org&via=raim.ist) because the internal room ID was very special:

`!test/v7 🐈️:maunium.net` (alias thingy is `#test/v7:maunium.net`)

The `/` and the emoji should be URL encoded (or just everything special) so that synapse doesn't misinterpret the `/` and the emoji doesn't cause weird issues.
That way, even if the room ID contains special characters, it should "just work" without having to resort to a workaround (manually URL encoding the room ID, so it's `%21test%2Fv7%20%F0%9F%90%88%EF%B8%8F%3Amaunium.net` instead).

[Solution for user ref](https://matrix.to/#/%23synadm%3Apeek-a-boo.at/%24LPTAauZIkJMAEHppw3GRQq0A-iGHc5WE92NimwT5OP4?via=jacksonchen666.com&via=maclemon.at&via=matrix.org&via=raim.ist), [Handy URL encode code snippet](https://stackoverflow.com/questions/40557606/how-to-url-encode-in-python-3/54135995#54135995)
Given the code needed to URL encode in python, I would put this label an "easy issue" but I'm not sure what changes are needed to make sure room IDs are URL encoded (there probably is also multiple places to also handle it sooooo).
Related issues in another project: https://github.com/Awesome-Technologies/synapse-admin/issues/111

**Comment by JacksonChen666** [comment]
thinking up some implementation details:

example of already done: https://github.com/JOJ0/synadm/blob/07113089d3b1bb2bbdcf1ec7ac2884c814ef3f59/synadm/api.py#L318

example of not done: https://github.com/JOJ0/synadm/blob/07113089d3b1bb2bbdcf1ec7ac2884c814ef3f59/synadm/api.py#L784

**Comment by JacksonChen666** [comment]
thinking up some implementation details...

example of already done: https://github.com/JOJ0/synadm/blob/07113089d3b1bb2bbdcf1ec7ac2884c814ef3f59/synadm/api.py#L318

example of not done: https://github.com/JOJ0/synadm/blob/07113089d3b1bb2bbdcf1ec7ac2884c814ef3f59/synadm/api.py#L784

my main idea is to apply URL encoding on user input that will be part of URLs.
maybe by extend a string so that it overwrites the `__format__` https://peps.python.org/pep-0498/#code-equivalence

(alternative: wrapper function that is basically f-strings, but it encodes all the user input things)
extending formatter:
https://docs.python.org/3.8/library/string.html#custom-string-formatting
https://peps.python.org/pep-3101/#user-defined-formatting
https://docs.python.org/3.8/library/functions.html#format

other links:
https://docs.python.org/3.8/library/functions.html#format
https://docs.python.org/3.8/reference/datamodel.html#object.__format__
https://peps.python.org/pep-0498/#code-equivalence

**Comment by JacksonChen666** [comment]
what about just making the `query` function handle the string formatting like `str.format` (`str` being an actual string object not formatted beforehand, it accepts any args for formatting (except data and other already existing) AND URL encodes user input or whatever)

**Comment by JOJ0** [comment]
Sounds like a good idea to fix it in a central location. Please go ahead with a PR, I'm looking forward to reviewing it!
